### ISSUE TITLE
Children route problem

### ISSUE THREAD

**Issue by ruelrule05** [leonardovilarinho/vue-acl#11]
I think validation fails for children routes when directly accessing them. If a route is visited using the <router-link> it does the validation, but if I access the URL directly or even refreshing the page, it redirects me to the parent route which is in my example below is the dashboard page.

e.g: 127.0.0.1:8080/user-list

`routes: [
   {
      path: '/',
      name: 'Dashboard',
      component: Dashboard,
      meta: {
         permission: 'any',
         fail: '/error'
      },
      children: [
         {
            path: '/user-list'
            name: 'Users',
            component: Users
            meta: {
               permission: 'view-users'
               fail: '/error'
            }
         }
      ]
   }
]`

**Comment by leonardovilarinho** [comment]
Hi,
for default, applications with vue no persist any data in browser, with it refresh page the data are lost. In you example, the permission is missing because no is persistense.

For fix it, storage the permission with localStorage or sessionStorage.
