### ISSUE TITLE
Passing string to `this.$access` fail

### ISSUE THREAD

**Issue by frangeris** [leonardovilarinho/vue-acl#12]
### Is this a bug report?

Yes

### Environment

1. `"vue-acl": "^2.1.0",`
2. `"vue": "^2.3.4",`

Then, specify:

### Steps to Reproduce

Just pass role as a string using `|` to `this.$access`

### Expected Behavior

Acts like passing an array

### Actual Behavior

Get into a loop and finish with an unknown error from vue.
<br>
![screenshot from 2017-07-11 09-56-21](https://user-images.githubusercontent.com/811381/28069363-98fa9478-661f-11e7-9763-1fd9b06fcaf4.png)

**_ps: This is happening just when I send the roles as string, not array, eg:_**

```javascript
this.$access('admin|user|owner')
```

**Comment by leonardovilarinho** [comment]
Hello,

this is not bug, but a default.

But I added this feature in plugin, see: 5d5e7f3   

Use the 2.1.10 version.

ps: use the & character for define multiple permissions, because | is sign to OR
