### ISSUE TITLE
url falls back without 'any'

### ISSUE THREAD

**Issue by phamvanthanh** [leonardovilarinho/vue-acl#14]
Hi @DannyFeliz,

Any child route (without any) in nested route falls back to parent ( with 'any')  after reload page. I does not keep the url. Is that my configuration problem?

**Comment by jgnovais** [comment]
hi @phamvanthanh in my project i type for all routers that i have to work it.

**Comment by phamvanthanh** [comment]
@jgnovais Is that right 'any' allow anyone to access? If yes, I am confused what It controls access when allowing all

**Comment by jgnovais** [comment]
@phamvanthanh  the fact is the 'any' permission, not means that your user has this permission. it is only to instantiate the vue-acl, he needs some permission to this

**Comment by leonardovilarinho** [comment]
@phamvanthanh you have what declare permission in all routes. The 'any' permission is only example, you have what define.
