### ISSUE TITLE
Permission undefined should not mean permission failed

### ISSUE THREAD

**Issue by muhammadsaeedparacha** [leonardovilarinho/vue-acl#16]
`router.beforeEach((to, from, next) => {
            const fail = to.meta.fail || '/'
            if (typeof to.meta.permission == 'undefined')
                return next(fail)
            else {
                if (!this.check(to.meta.permission))
                    return next(fail)
                next()
            }
        })`
I start my Application with 'any' permission. But then at bootstrap I call permissions from database which are like: customers.create, customers.read etc.
this.$access($permissions) results in 'any' permission getting lost. And now when I need to redirect at logout, or even my home page / which had 'any' permission requirement cannot be opened now.
I can create a pull request if you agree that undefined permission should allow routing

**Comment by Passionatedreamer** [comment]
Update: I think undefined permission should stop routing but permission defined as empty `permission: ''` should just mean no permission required. It will add one line in `check(permission)` function as
`if(permission == ''){return true}`

**Comment by leonardovilarinho** [comment]
Thank you for contribute!
