### ISSUE TITLE
Docs are not completely clear, can't get it to work, window freezes

### ISSUE THREAD

**Issue by jonagoldman** [leonardovilarinho/vue-acl#20]
Hi, reading the docs is not completely clear how to integrate with an existing app.
But looking at ```main.js``` in the demo app I see this:

```js
new Vue({
  el: '#app',
  router,
  render: h => h(Init)
})
```

Is ``` render: h => h(Init) ``` always needed? Is this the only way to make it work? Is there something inside Init.vue that is required?

--

Inside the ```Init.vue``` component I see:
```js
data() {
    return {active: this.$access()}
},
```
Is this always needed?

--

Is the ```permissions``` meta data inside the routes required for every route? What happens if I don't have this in a few routes?

I am just trying to figure out why its not working for me. The app gets stuck, nothing is shown, the browser freezes and I need to close the window.  I don't get any error or log so I don't know whats happening.

Thanks.

**Comment by leonardovilarinho** [comment]
The `render` attribute is default the VueJS, he display your application in screen.

-- 

```javascript
data() {
    return {active: this.$access()}
},
```
This is only an example, he get current permission from your app.

--
Yes, always your routes have the metadata `permissions`. If you not use, the route no work.

**Comment by jonagoldman** [comment]
Ok, so I have done as you said but for some reason the app is refusing to load.

Do I need a permissions meta data in each route or only one in the parent route is enough just for testing?
