### ISSUE TITLE
 router.beforeEach is not a function

### ISSUE THREAD

**Issue by mvatansever** [leonardovilarinho/vue-acl#23]
Hi there,

I'm newly at VueJS and front-end development so I can't solve the problem with researching. I install this package and put the import and use lines to my project like this:

```
import VueRouter from 'vue-router'
import Acl from 'vue-acl'
Vue.use(VueRouter)
Vue.use( Acl, { router: VueRouter, init: 'any' } )
```

But its return to this error I wrote at the title of the issue. My project use VueRouter's **2.7.0** version and VueJS version is **2.4.3** . I checked vue-router.js file has the "beforeEach" function and the router working before to install this package. 

So what configurations may I do? Or how to solve this problem?

**Comment by leonardovilarinho** [comment]
Hi, you passed `VueRouter` to `VueAcl`, you have declare the `router` object with settings frio VueRouter and tour routes, and pass thia object to plugin. Please, see my example in Readme.md.

**Comment by mvatansever** [comment]
Thanks for the reply. Yes, I made a mistake when apply the README. Changed with the const variable and fixed this issue.

But now I have a new error like this:
> vue-router.esm.js?880d:1832 RangeError: Maximum call stack size exceeded

My finished code is here:
```
import VueRouter from 'vue-router'
import Acl from 'vue-acl'
import routes from './routes/routes'

Vue.use(VueRouter)

// configure router
const router = new VueRouter({
  mode : 'history', // url pattern '#' for remove
  routes, // short for routes: routes
  linkActiveClass: 'active'
})

Vue.use(Acl, {router: router, init: 'any'})

/* eslint-disable no-new */
new Vue({
  el: '#app',
  render: h => h(App),
  router
})
```

It's fixed when I remove the "Acl" from the code. How may I resolve this issue?

**Comment by leonardovilarinho** [comment]
Please, show me your routes.js file.

**Comment by mvatansever** [comment]
I cleaned and only this routes stay but the problem is continues (fixed when remove the Acl from main.js)
```
import DashboardLayout from '../components/Dashboard/Layout/DashboardLayout.vue'
const routes = [
  {
    path: '/panel',
    component: DashboardLayout,
    redirect:'/panel/anasayfa',
    meta: {
        permission: 'view-user|store-user',
        fail: '/error'
    }
  }
]

/**
 * Asynchronously load view (Webpack Lazy loading compatible)
 * The specified component must be inside the Views folder
 * @param  {string} name  the filename (basename) of the view to load.
 function view(name) {
   var res= require('../components/Dashboard/Views/' + name + '.vue');
   return res;
};**/

export default routes
```

**Comment by leonardovilarinho** [comment]
Try comment the `redirect:'/panel/anasayfa'` line, the VueRouter can be enterning in loop infinite because it.
