### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by codeitlikemiley** [leonardovilarinho/vue-acl#24]
Hi, First Of All Thanks for this plugin...

I had quite few questions i think is not documented, i hope you can answer it thanks

Let say i Define a Default permission guest
```
Vue.use( Acl, { router: Router, init: 'guest' } )
```

Adding a New permission is such 
route.js
```
{
    path: '/Dashboard',
    component: require('./components/Dashboard.vue'),
    meta: {
      permission: 'user' ,fail: '/error'
    }
  },
```

You Had this $can protoype...

How does this $can determine if im a user?

How do i put the logic stuff to determine if it can access or if it is a user?

I wanna do a check for a token if this is a user... So i can let them passed that router...

So how do i go about it?

Coz if i do $access() i get guest...

Even if i had the token already in the local storage...

So Can you explain how can put logic to determine the permission?

**Comment by leonardovilarinho** [comment]
Hi,

I no understand your question, what you want do?

You have the current permission in localStorage, and want build an "if else" with it?

**Comment by codeitlikemiley** [comment]
yes

**Comment by leonardovilarinho** [comment]
Use `$can` method, follow this example:

```
...
mounted() {
    this.myAccessIs()
},
methods: {
    myAccessIs() {
        if(this.$can('admin'))
            alert('current user is admin')
        else
            alert('current user is other')
    }
}
...
```
