### ISSUE TITLE
Page Refresh

### ISSUE THREAD

**Issue by joubraga** [leonardovilarinho/vue-acl#27]
Boa tarde fera blz ? (Ótimo plugin !!!)
Cara eu sei que não faz muito sentido o refresh na tela, porém reparei que ao dar refresh a página sempre irá para página de Fail que estiver configurado. Teria alguma forma de ao dar refresh na tela continuar na mesma ? 

Vlw !!

**Comment by leonardovilarinho** [comment]
Boa tarde, @joubraga

Você está usando qual versão do plugin? A partir da versão 1.0.9 eu adicionei o armazenamento em sessionStorage, assim mesmo recarregando a página ele continua com a permissão. Veja se o seu sistema usa uma versão posterior a essa.

Se usa, e mesmo assim estiver com esse problema, a solução do problema é no `main.js`, nele você pode recuperar a permissão do usuario logado, seja da sua API ou Vuex, e adicionar ao plugin usando o método `$access`

**Comment by joubraga** [comment]
Primeiramente boa tarde e obrigado por responder e ainda por uma maneira bem rápida !!!!!
Cara dei uma olhada na versão do plugin e ela está na 2.2.2....
Não estou conseguindo colocar em meu main.js Peço até perdão, pois sou novo nesta área de Vuejs :(

Pois quando estou utilizando ele está falando que o meu this.$access is not a function

Deveria importar o ACL aqui  colocar os seguintes comandos abaixo : 
   import Acl from 'vue-acl'
   Vue.use(Acl, { router: router, init: 'any' }) 

?????

O meu main está da seguinte forma: 

import Vue from 'vue'
import App from './App'
import router from './router/router'
import store from './store'
import * as interceptors from './services/interceptors'

// this.$access deveria estar aqui mesmo ????
this.$access('perfil do cara') 

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  interceptors,
  VueSweetAlert,
  template: '<App />',
  components: { App },
  mounted () {
    this.$access('admin')
  }
})


Vlw cara obrigado pela atenção !!!

**Comment by leonardovilarinho** [comment]
Bom, a chamada do método `$access` deve ser feita dentro de um componente, no caso você usaria apenas no método `mouted` ali, e não antes do `new Vue`, pois antes desse momento você não tem um componente. Então basta apagar essa linha `this.$access('perfil do cara')` e na linha `this.$access('admin')`, no lugar de `admin` recuperar a permissão atual, seja do `localStorage` ou do seu back-end.

**Comment by joubraga** [comment]
Bom dia @leonardovilarinho !!
Obrigador por responder porém mesmo fazendo isso, ainda não funcionava.
Mas acabei dando uma olhada no código e vi que o problema não era isso,  e sim quando eu usava o Vue.use(Acl, { router: router, init: 'any'})

Como você pode ver o init: 'any' estava como permissão **any**, e quando eu entrava em uma rota que era obrigado a ter x permissão ele não batia com a permissão e redirecionava para a página inicial que eu tinha setado. Logo então alterei init: 'any', para permissão atual, conforme mostra abaixo: 

Vue.use(Acl, { router: router, init: '**SessionStorage.acesso**' })

E com isso acabou resolvendo o problema !!
Obrigado pela sua ajuda !!! e espero que isso ajude alguém no futuro ai  👯
