### ISSUE TITLE
#27 Page refresh

### ISSUE THREAD

**Issue by joubraga** [leonardovilarinho/vue-acl#28]
Primeiramente boa dia e obrigado por responder e ainda por uma maneira bem rápida !!!!!
Cara dei uma olhada na versão do plugin e ela está na 2.2.2....
Não estou conseguindo colocar em meu main.js Peço até perdão, pois sou novo nesta área de Vuejs :(

Pois quando estou utilizando ele está falando que o meu this.$access is not a function

Deveria importar o ACL aqui colocar os seguintes comandos abaixo :
import Acl from 'vue-acl'
Vue.use(Acl, { router: router, init: 'any' })

?????

O meu main.js está da seguinte forma:

import Vue from 'vue'
import App from './App'
import router from './router/router'
import store from './store'
import * as interceptors from './services/interceptors'

// this.$access deveria estar aqui mesmo ????
this.$access('perfil do cara')

/* eslint-disable no-new */
new Vue({
el: '#app',
router,
store,
interceptors,
VueSweetAlert,
template: '',
components: { App },
mounted () {
this.$access('admin')
}
})

Vlw cara obrigado pela atenção !!!

**Comment by leonardovilarinho** [comment]
Respondido na issue #27, por favor não crie duas issues para o mesmo problema.
