### ISSUE TITLE
router.beforeEach is not a function

### ISSUE THREAD

**Issue by Timtech4u** [leonardovilarinho/vue-acl#34]
I keep getting: router.beforeEach is not a function 
on my console.

**Comment by leonardovilarinho** [comment]
Please check your steps:

1. Install and configure VueRouter with `permission` meta.
2. Install and import VueAcl with `init` route and `router` instance.
3. Use `$can` or `this.access` to control acl.

If this error continue, please show me your code.

**Comment by ShrJoshi28** [comment]
I have error this-

Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1_vue_router__.a.beforeEach is not a function

How to solve this error in vue js

**Comment by uno2xx** [comment]
I have the same issue when i import the acl.js after the router.

<img width="507" alt="screen shot 2019-02-14 at 1 50 54 am" src="https://user-images.githubusercontent.com/1035889/52732480-4efcd500-2ffb-11e9-98e5-e7523347f985.png">

**Comment by ShrJoshi28** [comment]
Try this - here formSubmit is login method.
export function requireAuth(to, from, next) {
  if (!formSubmit()) {
    next({
      path: '/',
      query: { redirect: to.fullPath }
    });
  } else {
    next();
  }
}
