### ISSUE TITLE
Where is this.access to be set? 

### ISSUE THREAD

**Issue by joeseeley** [leonardovilarinho/vue-acl#35]
I have read the documentation and done the setup, but I'm unclear where I should actually be setting access, and how?  I have tried setting in the mounted callback of App.vue, but this does not work. 

Currently, I am just trying to very simply set it to a static string in mounted something like this.

    `mounted() {
        this.access = 'admin';
     }` 

In a real use case I would like to set this when mounted use an axios API call.

**Comment by AmazingDreams** [comment]
It believe it must be an array.

I do this in App.vue as well and have a watch on a 'is logged in' property to request permissions / roles from the server.

**Comment by leonardovilarinho** [comment]
@joeseeley show me your code with API call, and what is error returned?

**Comment by joeseeley** [comment]
@leonardovilarinho 

I think something was cached on my page; it started working without any change.  I do have a couple of other questions though.

1.  I noticed from some of the issues and documentation floating around you could set access like `this.$access('admin');`.  I tried that and get an error `$access is undefined`.  It looks like this was removed from the plugin?  Can you confirm?

1. I am using Vuex for my project.  I realize vue-acl doesn't require Vuex, but from of the comments it appears it does/did support it, but not clear of the proper way to integrate it with Vuex?  Right now I'm sort of bypassing Vuex for authorizations, but I'm not sure this is ideal.  It looks something like this.

 --

     In App.vue
    mounted() {
        this.$store.dispatch('setUser', this.access);
    }

    // In Vuex store
    actions: {
        setUser(context, access) {
            service.isLoggedIn()
              .then((response) => {
                  // User is pulled from API and has user & roles which are
                  // stored in Vuex as **user**
                  context.commit('SET_USER', response.data.user);
                  // Updating access to have the correct roles rather than the default,
                  // but it would be nice if this could **just use a Vuex state**?
                  access.length = 0;
                  response.data.user.roles.forEach(function(el) { access.push(el); });
              });
        }
    }`

**Comment by leonardovilarinho** [comment]
Hi @joeseeley

The access variable is only editable in your Vue component, to edit it you should have the getUser in store and retrieve the current permission to store in variable.

**Comment by ErickZH** [comment]
Hi, I use `this.$acl.change(my_role)` for change the permission obtained from the API.

Regards from Mexico city 🌮
