### ISSUE TITLE
How to prevent going to fail page during App creation/mounting?

### ISSUE THREAD

**Issue by joeseeley** [leonardovilarinho/vue-acl#36]
I have vue-acl setup and for the most part everything is working now.  One issue though is if a user tries to go to go directly to a restricted page they end up at the fail route.

It looks something like this today.

`Vue.use(VueAcl, { router: router, init: 'public', fail: '/access_denied'});`

Then in the App.vue the login and "real" credentials will be set asynchronously from the backend during mounting the app.

    mounted() {
        // Eventually this will set correct access in a Promise
        this.$store.dispatch('setUser', this.access);
    }

If the user starts by going to the home page then they don't see an issue.  They hit the home page, login, now they can go to the correct sub-routes they have been granted access to.

But instead a user wants to go directly to the sub-route (maybe they have bookmarked for example).  

Now what happens is
1) User goes to `/#/orders`
2) router.beforeEach is called and redirects users to `/#/access_denied`
3) User's access is set correctly
4) User has to navigate back to the page manually
5) Unhappy users :(

Going to the fail route makes sense, why it is happening; I'm just wondering if there is some way here to handle this so that the requested path can somehow be captured and the user redirected back to the requested path when the access is finally resolved?

**Comment by leonardovilarinho** [comment]
Hello there,

you can use the [programmatic navigation](https://router.vuejs.org/en/essentials/navigation.html) from the `vue-router` for this issue, use `router.go(-1)` if your user is valid, he go redirect to correct page.

A tip, in `access_denied` you can write "await, verifying your credentials...", to user know that need wait.
