### ISSUE TITLE
Changed permissions revert to initial values on router navigation

### ISSUE THREAD

**Issue by martinhbramwell** [leonardovilarinho/vue-acl#37]
Estimado Leonardo,

I'm encountering a problem with `vue-acl`, and cannot tell if it is my own fault, or not.

I initialise with:

```
Vue.use( Acl, { router: Router, init: ['public', 'visitor'] } )
```
(with 'visitor' added temporarily for debugging purposes)

The user follows log in sequences I created and further permissions are supplied from the server.  I update `vue-acl` with, for example : 

```
console.log(userPrivs);  // ['public', member', 'staff']
this.access = userPrivs;
```
This works fine, until I use the router to switch components, at which point permissions revert automaticaly back to 

```
['public', 'visitor']
```

I tried to intercept this change with the hook `router.beforeResolve` which is ...

>  called right before the navigation is confirmed, after all in-component guards and async route components are resolved.

... but the reversion still occurs.

Is this something you have seen when `vue-acl` is used incorrectly, is it an issue with `vue-acl` itself, or is it unknown to you 'til now?

**Comment by mazeeblanke** [comment]
i am having the same issue, @martinhbramwell please have you found a fix ?

**Comment by mazeeblanke** [comment]
@martinhbramwell i was able to get it working with version 2.2.3

**Comment by leonardovilarinho** [comment]
Hi, as the project is only maintained by one person it becomes difficult to respond fast. Because I have other plugins and tasks to do.

I am planning to rewrite the plugin, but as @mazeeblanke mentioned, use version 2, because in 3 we had changes regarding this treatment.
