### ISSUE TITLE
Problema no vue-acl

### ISSUE THREAD

**Issue by NomiasSR** [leonardovilarinho/vue-acl#44]
Boa tarde Leonardo, tudo na paz cara? Então, sem muita demora... estou tentando implementar esse exemplo seu:
https://leonardovilarinho.github.io/vue-acl/

Mas não funciona de jeito nenhum (grande parte por causa da minha inexperiência). Quando eu tento importar a linha:
import VueAcl from 'vue-acl'

me dá sempre esse erro:
 [ts] Não foi possível localizar o arquivo de declaração para o módulo 'vue-acl'. 
'c:/sistema/node_modules/vue-acl/dist/index.js' tem implicitamente um tipo 'any'.
Tente `npm install @types/vue-acl`, se existir, ou adicione um novo arquivo de declaração (.d.ts) 
que contenha `declare module 'vue-acl';`
module "c:/sistema/node_modules/vue-acl/dist/index"

Já tentei de várias maneiras refazer o exemplo passo-a-passo e também já tentei fazer a correção de acordo com o que está escrito na mensagem de erro, ambos sem sucesso.
Gostaria de pedir a sua ajuda para a solução desse problema.
Obrigado 

Paulo Ramos

**Comment by leonardovilarinho** [comment]
Olá @NomiasSR 

Não tive tempo de atualizar a documentação do site, ela está mostrando o tutorial da versão antiga do plugin, ele foi totalmente reescrito e a sintaxe trocada, então por isso não está funcionando.

Você pode usar a nova versão, e seguir o tutorial daqui: https://github.com/leonardovilarinho/vue-acl

Ou executar um `npm install vue-acl@3.0.4` para instalar a versão antiga do plugin com essa sintaxe do tutorial que você usou.

**Comment by NomiasSR** [comment]
Blz cara, eu fiz o tutorial baseado nesse exemplo, mas a minha dúvida é como eu posso setar e checar as permissions de um usuário?

**Comment by leonardovilarinho** [comment]
Na versão 3.0.4 ou anterior você pode atribuir uma permissão apenas trocando o valor da variável `access` de qualquer componente. exemplo: `this.access = 'admin'`.

Para verificar as permissões você pode usar o método `$can`, exemplo: `if (this.$can('admin))`  ou `v-if="$can('admin')"` , a condição será true se a permissão atual tiver `admin`.

**Comment by NomiasSR** [comment]
Mais uma observação Leonardo, quando eu crio o arquivo acl.js com essas linhas:
import Vue from 'vue'
import { AclInstaller, AclCreate, AclRule } from 'vue-acl'
import router from './router'

Vue.use(AclInstaller)

export default new AclCreate({
  initial: 'public',
  notfound: '/error',
  router,
  acceptLocalRules: true,
  globalRules: {
    isAdmin: new AclRule('admin').generate(),
    isPublic: new AclRule('public').or('admin').generate(),
    isLogged: new AclRule('user').and('inside').generate()
  }
})

Estou tento a seguinte mensagem de erro:
[ts] Não foi possível localizar o arquivo de declaração para o módulo 'vue-acl'. 'c:/sistemas/node_modules/vue-acl/dist/vue-acl.js' tem implicitamente um tipo 'any'.
  Tente `npm install @types/vue-acl`, se existir, ou adicione um novo arquivo de declaração (.d.ts) que contenha `declare module 'vue-acl';`
[ts] Não foi possível localizar o arquivo de declaração para o módulo 'vue-acl'. 'c:/sistemas/node_modules/vue-acl/dist/vue-acl.js' tem implicitamente um tipo 'any'.
  Tente `npm install @types/vue-acl`, se existir, ou adicione um novo arquivo de declaração (.d.ts) que contenha `declare module 'vue-acl';`

Como eu posso resolver isso?

Obrigado pela ajuda cara

Paulo Ramos

**Comment by NomiasSR** [comment]
opa Leonardo, fiz calmamente o exemplo que você passou e está funcionando tudo bem até o momento. Eu gostaria de saber como posso colocar na rota validações para mais de uma rule em uma rota, por exemplo:

 mode: 'history',
  routes: [
    {
      path: '/hello',
      name: 'hello',
      component: Hello,
      meta: {
        rule: 'isPublic', 
      }
    },

Como eu posso colocar nessa rota validação de rule 'isPublic' ou 'isFinanceiro' e se o financeiro tem permissão de fazer tudo (delete, updade, insert) e o 'isPublic' só pode pesquisar, por exemplo?
