### ISSUE TITLE
and method not working

### ISSUE THREAD

**Issue by yakupars** [leonardovilarinho/vue-acl#46]
When try this when currentAcl is 'ok',
`isAbs: new AclRule('not').and('ok')` it is working but when do this,
`isAbs: new AclRule('ok').and('not'),` it is not working (iexpected)

**Comment by SergeyMiracle** [comment]
@leonardovilarinho is this project still maintained?

**Comment by leonardovilarinho** [comment]
@yakupars I didn't quite understand your doubt.

the `not` modifier can only used in you Vue component. This modifier invert your rule verification, e.g:

```vue
<section v-if="$acl.not.check('isAbs')">
  Not ABS content
</section>
```

The `section` is displayed only if your current permission is not valid in `isAbs` rule.

**Comment by leonardovilarinho** [comment]
@SergeyMiracle as it is a personal project I launch updates when I have time, since people only ask and do not send PR. At the moment it is a long time without update because I did not see anything that has to change.

**Comment by leonardovilarinho** [comment]
@SergeyMiracle I launch updates when I have time.

**Comment by SergeyMiracle** [comment]
@leonardovilarinho thx for you response :) 
Well if there is updates i can stick with you package really, just don't wanna use something that is already dead 😄

**Comment by chaoyenpo** [comment]
@leonardovilarinho please, can you update? 

```javascript
// checker.js, 29 Lines
rule.forEach(and => valid = valid && current.includes(and))
```

**Comment by yakupars** [comment]
@chaoyenpo I have already done this. He declined at first but now he knows what is wrong I believe...
https://github.com/arsdevelopment/vue-acl/blob/f0060fe4c5a194b5617bababe230a87ace03f4e9/source/checker.js#L29

**Comment by chaoyenpo** [comment]
@yakupars 

#47 package author change, I don't think these should exist here, right?

```
-  "author": "Leonardo Vilarinho",
+  "author": "Yakup Arslan",
```

**Comment by leonardovilarinho** [comment]
I declined the PR because you changed the name from package. I requested changes in your PR, but you not answer. The `vue-acl` has updated with fix this issue, @yakupars your name has added in contributors list.
PS: sorry everybody because my simple English.
