### ISSUE TITLE
Atualização da página

### ISSUE THREAD

**Issue by DaniloTurini** [leonardovilarinho/vue-acl#48]
Quando faço um refresh na página ele volta da permissão para a inicial, gostaria de saber se tem como  ao atualizar uma página estar a permissão que estava antes de atualizar?

**Comment by leonardovilarinho** [comment]
Olá @DaniloTurini 

Você pode guardar em `sessionStorage`  ou `IndexedDB`, porém o ideal é pegar da API. Para isso, na instância raiz do Vue no arquivo `main.js` crie um `mounted` ou `created` chamando o método que autentica o usuário na API e retorna a permissão ou então pegue a permissão do `sessionStorage`  ou `IndexedDB`.

Mais ou menos assim no `main.js`:

```javascript
new Vue({
  acl,
  router,
  store,
  render: h => h(App),
  mounted () {
    const permission = // pega da api ou storage do navegador

    // se não encontrou permissão então coloca a padrão
    if (permission === null) return this.$acl.change('public')

    this.$acl.change(permission)
  }
}).$mount('#app')
```
