### ISSUE TITLE
Refresh Page

### ISSUE THREAD

**Issue by DaniloTurini** [leonardovilarinho/vue-acl#49]
Leonardo, fiz igual vc me falou, mas continua a redirecionar para a rota de login que foi a rota que defini no arquivo acl.js.

import Vue from 'vue';
import { AclInstaller, AclCreate, AclRule } from 'vue-acl';
import router from './router';

Vue.use(AclInstaller);

export default new AclCreate({
    initial: 'public',
    notfound: '/entrar',
    router,
    acceptLocalRules: true,
    globalRules: {
        isAdmin: new AclRule('admin').generate(),
        isCliente: new AclRule('cliente').generate(),
        isParceiro: new AclRule('parceiro').generate(),
        isContador: new AclRule('contador').generate(),
        isLogged: new AclRule('admin').or('cliente').or('parceiro').or('contador').generate(),
        isPublic: new AclRule('public').or('admin')
                          .or('cliente').or('parceiro')
                          .or('contador').generate()
    }
});

o meu arquivo main.js ficou assim:
new Vue({
    router,
    store,
    acl,
    el: '#app',
    render: h => h(App),
    mounted () {
        if (localStorageGetItem('token') != null)  {
            this.doRefresh();
        }
    },
    methods: {
        ...mapActions('auth', ['doMe']),
        async doRefresh () {
            await this.doMe();

            if (this.userTipo != '') {
                this.$acl.change(this.userTipo);
            }
        }
    },
    computed: {
        ...mapGetters('auth', ['userTipo'])
    }
});

Gostaria de saber se tem alguma dica para quando eu fizer um refresh na página continue na mesma sem redirecionar.

**Comment by leonardovilarinho** [comment]
está correto esse `localStorageGetItem`? Não seria `localStorage.getItem`?
