### ISSUE TITLE
Version 4.0.5 with no module

### ISSUE THREAD

**Issue by rcosta-gcare** [leonardovilarinho/vue-acl#50]
I think the version 4.0.5 was built without acl module.

![screen shot 2018-09-17 at 10 43 59 am](https://user-images.githubusercontent.com/19914165/45630393-9d1aa600-ba66-11e8-8daa-20f9f4b53d9f.png)

This is the directory

**Comment by leonardovilarinho** [comment]
Thanks, I fixed it in 4.0.6 version. Please update in your project.
