### ISSUE TITLE
Possible Memory Leak - Missing beforeDestroy Method

### ISSUE THREAD

**Issue by Tob0t** [leonardovilarinho/vue-acl#52]
I really love your package, but I think I found a memory leak which sometimes crashes our app. If you use that package in combination with vue-router and change routes many times you can see that the components are not destroyed properly.
# Repro Steps:
* Go to Home route
* Check Chrome Dev Tools -> Memory -> Take snapshot and check the number of Vue Components
* Switch to different route
* Switch back and take another snapshot -> The number increased
* So it means, that the components are not destroyed properly

The reason for that is that you are missing to destroy the listener of the event bus in `beforeDestroy()` method. More Info and repro fiddle can be found here: https://github.com/vuejs/vue-router/issues/1181

It is solved by just adding these lines to the `mixin.js`:
```
beforeDestroy() {
  EventBus.$off('vueacl-permission-changed')
}
```

Let me know if you need a pull request ;)

**Comment by leonardovilarinho** [comment]
I publish in NPM, #aba7cab65426a00a85eeab29e638606265fc259a

Thanks man!

**Comment by dastiw1** [comment]
code of `EventBus.$off('vueacl-permission-changed` is incorrect. I found memory leak. Two callback functions with same functionality is not the same. Callback in $on and $off is not the same functions. You must define function first.

PS. Sorry for my english

**Comment by leonardovilarinho** [comment]
Sorry for the delay. I really hadn't thought about it, I fixed it in the last commit. Thank you for the warning.
