### ISSUE TITLE
change initial role after store subscribe

### ISSUE THREAD

**Issue by jakubm95** [leonardovilarinho/vue-acl#54]
Hello, how to change initial role after store subscribe mutation??
this.$acl.change(mutation.payload.role)
don't work

my acl.js file

`import Vue from 'vue'
import { AclInstaller, AclCreate, AclRule } from 'vue-acl'
import router from './router'
import { store } from './_store'
Vue.use(AclInstaller)

if(!!store.state.account.user){
  var currentRole = store.state.account.user.role
}else{
  var currentRole = '*'
}

export default new AclCreate({
  initial: currentRole,
  notfound: '/dashboard',
  router,
  acceptLocalRules: true,
  globalRules: {
    isAdmin: new AclRule('ROLE_ADMIN').generate(),
    isLogged: new AclRule('ROLE_USER').generate(),
    isPublic: new AclRule('*')
  }
})

store.subscribe((mutation, state) => {
  if (mutation.type === 'account/loginSuccess') {
    this.$acl.change(mutation.payload.role)
    console.log(mutation.payload.role)
  }
})`

**Comment by leonardovilarinho** [comment]
Hello @jakubm95 , sorry for the delay.

Because ACL is a Vue library, `this.$acl` variable is accessible only within Vue components. So I suggest you do the permutation on the Vue component where the mutation `account/loginSuccess` is called.
