### ISSUE TITLE
Vue-acl com Firebase?

### ISSUE THREAD

**Issue by filipeluiz** [leonardovilarinho/vue-acl#55]
Ola pessoal,

Gostaria de fazer um banco de dados do firebase com vue-acl, mas como faço pra identificar se o usuário é admin ou não. Deveria usar SDK admin do firebase? se sim, por favor me passar tutorial ou algo assim, pois tenho dificuldade criar um servidor do lado de back-end(sou front).

**Comment by leonardovilarinho** [comment]
Ola @filipeluiz ,

desculpe a demora no retorno, andei ocupado. Você precisa ter a autenticação no Firebase e o usuário precisa ter uma propriedade `type` para informar a qual grupo de usuário ele pertence.

No ´main.js`, você irá pegar o usuário do Firebase (com esse tutorial https://firebase.google.com/docs/auth/admin/manage-users?hl=pt-br) e ao pegar esse retorno, basta usar `this.$acl.change('isAdmin')` se o usuário for admin, ou trocar para outra regra de ACL de acordo com o usuário que o Firebase retornou.
