### ISSUE TITLE
URL With Documentation

### ISSUE THREAD

**Issue by jdriesen** [leonardovilarinho/vue-acl#57]
Hi sir,

First of all, congratz with the development of this software.
Just a question

The URL on top of your GitHub page is forwarding us to https://leonardovilarinho.github.io/vue-acl/ (and shows us the docu)

Is it possible this link is still referring to the OLD documentation ?

Thanks in advance for your reply,

KInd regards,

Johnny

**Comment by leonardovilarinho** [comment]
Hello @jdriesen 

yes, this url show the old documentation. I'm little time for update this :(
