### ISSUE TITLE
How can I add multiple rule in router

### ISSUE THREAD

**Issue by jsinhSolanki** [leonardovilarinho/vue-acl#58]
Hey great job,

I get console errro if I add multiple rule as array in `meta`
```
{
    path: '/dashboard',
    name: 'dashboard',
    component: () => import('./views/Dashboard.vue'),
    meta:
    {
        rule: ['isAdmin', 'isEditor']
    }
},
```
When I visit this route I got console error like below:
![capture](https://user-images.githubusercontent.com/31243533/53953034-601b9c00-40f8-11e9-9f28-9c1b84d1c4f2.PNG)

**Comment by tiagosimoesdev** [comment]
I have the same question , have you found out ?

**Comment by jsinhSolanki** [comment]
@tiagosimoesdev No.
Instead, I adjusted my roles.

**Comment by leonardovilarinho** [comment]
Hi,

this is not possible, the rule must be a String or an instance of AclRule. In turn, AclRule allows multiple rules, for example for rule "login and write permission" use:

```javascript
globalRules: {
    isLoggedAndWrite: new AclRule('user').and('write').generate()
  },
```

Already for rule "logged in, but without write permission" use:

```javascript
globalRules: {
    isLoggedNotWrite: new AclRule('user').and('nowrite').generate()
  },
```

**Comment by phamchitrung05** [comment]
It increases the number of rules in the code
