### ISSUE TITLE
Computed property not working

### ISSUE THREAD

**Issue by jsinhSolanki** [leonardovilarinho/vue-acl#59]
Hi there,

I want to display sidebar item conditionally so I have `v-if` in `template` tag. But computed property is not reactive??

```
<div ... v-if="canSee">
..
</div>
```

```
    computed: {
    	canSee() {
                       console.log('test);
    			return this.$acl.check(this.$router.match(this.to).meta.rule)
    	}
    },
```

`test` is only logged for first time. When I change role using radio button, computed property is not recalculated???

I tested it again. Actually it's not updating state in my component.
`{{ $acl.get[0] }}` this is not working in that component. However in other page it works.

**Comment by leonardovilarinho** [comment]
I created a method of doing something similar in commit b9e96f0f6bdadc060d8ea18030dbb95634084091. 
Use the following code:

```javascript
mounted () {
  this.$acl.onChange = newPermission => {
    console.log('Has changed to', newPermission)
  }
}
```
