### ISSUE TITLE
Provável conflito com Webpack

### ISSUE THREAD

**Issue by douglasrolim** [leonardovilarinho/vue-acl#61]
Olá! Estou recebendo após incluir o acl na instancia do Vue.

`700:110 Uncaught SyntaxError: Unexpected token :
    at Object.<anonymous> (app.js:5253)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at Object.eval (assert.js?37e3:69)
    at eval (699:492)
    at Object.<anonymous> (app.js:5247)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (checker.js?28ff:8)
    at Object.<anonymous> (app.js:5240)`

Meu acl:
```
import Vue from 'vue'
import { AclInstaller, AclCreate, AclRule } from 'vue-acl'
import router from '../router'

Vue.use(AclInstaller)

export default new AclCreate({
  initial: 'public',
  notfound: '/',
  router,
  acceptLocalRules: true,
  globalRules: {
    isAdmin: new AclRule('admin').generate(),
    isLayerManager: new AclRule('layer-manager').or('admin').generate(),
    isPublic: new AclRule('public').or('admin').generate()
  }
})

```

Meu arquivo de rotas:
```
import Vue from 'vue'
import Router from 'vue-router'
import Main from '@/components/Main'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'Main',
      component: Main,
      meta: {
        rule: 'isPublic'
      }
    }
  ]
})
```

Meu arquivo main:
```
import Vue from 'vue'
import Vuex from 'vuex'
import App from './App'
import router from './router'
import Vuetify from 'vuetify'
import store from './stores'
import acl from './acl'


Vue.use(Vuex)

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  i18n,
  el: '#app',
  store,
  router,
  acl,
  components: {App},
  template: '<App/>'
})
```

Como poderia resolver esse problema?

**Comment by leonardovilarinho** [comment]
Não conseguir identificar nenhum erro, testei em um projeto limpo com o mesmo código, pode ser que exista algum erro de sintaxe em outra parte do código da aplicação. Poderia subir a aplicação com erro em algum repositório para eu ver para você?

**Comment by douglasrolim** [comment]
Enviei o convite para o repositório. Agradeço toda a atenção.

**Comment by leonardovilarinho** [comment]
Era um import que foi parar no `vue-acl` sem querer por causa do autocomplete do meu editor de texto.

Corrigi aqui, basta atualizar para a versão 4.1.0, note também que nesse versão foi adicionada a middleware, para pegar facilmente dados da api e trocar a permissão de acordo com o retorno.
