### ISSUE TITLE
Dúvida no uso com perfis autenticados

### ISSUE THREAD

**Issue by gomes-fdr** [leonardovilarinho/vue-acl#62]
Boa tarde,

Estou utilizando seu plugin em conjunto com uma API onde, eu faço uma autenticação(login) e recebo como resposta o perfil do usuário logado.

Gostaria de habiltar/desabilitar determinadas funcionalidades em função deste perfil, hoje nos componentes tenho feito desta maneira para tentar atribuir um perfil e usar a permissão correta:

this.access = 'Psicologo'

Quando imprimo $acl.get no ponto de entrada do meu app ele está com ["Publico"] que é a permissão padrão para visualizar a tela de login.

Qual seria a melhor maneira de encaixar essa associação do perfil devolvido pela API para o usuário logado?

Parabens pelo trabalho.

**Comment by leonardovilarinho** [comment]
Olá,

o uso de `this.access` é para versão 3 ou menor, a partir da versão 4 do plugin é usado o método `this.$acl.change()`, tente usar `this.$acl.change('Psicologo')` e veja se funcione.

Essa alteração foi realizada para encapsular todos os métodos e atributos do plugin dentro de `$acl`.

**Comment by gomes-fdr** [comment]
Bom dia,
Funcionou perfeitamente, muito obrigado.
