### ISSUE TITLE
0: Unable to get property 'beforeEach' of undefined or null reference

### ISSUE THREAD

**Issue by sniperadmin** [leonardovilarinho/vue-acl#69]
stuck for 10 hours!

**Comment by hacktivista** [comment]
this is because 
https://github.com/leonardovilarinho/vue-acl/blob/b9e96f0f6bdadc060d8ea18030dbb95634084091/source/router.js#L14
runs previous to your code... prefer to use the `beforeRouteLeave` trigger

**Comment by leonardovilarinho** [comment]
@hacktivista Thanks, I fixed that.

Sorry for the delay and my English
