### ISSUE TITLE
Your example code

### ISSUE THREAD

**Issue by jdriesen** [leonardovilarinho/vue-acl#75]
Hi Leonardo,

Can you please update your example code ?

- The 'admin' page is having the title 'About"

- Whatever I'm trying, I can't simulate the 'NotFound' situation

- Changing the permission doesn't have any impact ...
In ALL circumstances, I still can reach the Admin page ..

Thanks in advance for your effort,

Kind regards,
Johnny Driesen
Belgium

**Comment by leonardovilarinho** [comment]
Hi,

Unfortunately I have the short time to keep projects open source, especially to take care of examples and documentation.

On the notfound route, it was a package bug, it was fixed in the latest version.

Here's a simple new demo: https://github.com/leonardovilarinho/demo-acl
