### ISSUE TITLE
How to conditionally set the permission to something other than 'any' on initial page load

### ISSUE THREAD

**Issue by sjordan1975** [leonardovilarinho/vue-acl#8]
How do I set the permission to something other than 'any' on initial page load?

I some instances a user of my app might have a permalink. For example:
app.domain.com/bookmark/some-id

If the user is already logged into my app (for example window.localStorage.getItem('token') returns valid session), then I want to set permission to something like 'user'

I tried added the following in the mounted method of the Vue instance, but did not work (did not seem to override the 'any' permission set in initialization):

```
import Vue from 'vue'
import App from './App.vue'
import VueRouter from 'vue-router'
import routes from './routes' // my routes are stored here
import VueAcl from 'vue-acl'

Vue.use(Resource)
Vue.use(VueRouter)

const router = new VueRouter({
    mode: 'history',
    routes: routes,
    linkActiveClass: 'isActive'
})

// ACL middleware
Vue.use(VueAcl, {router: router, init: 'any'})

new Vue({ 
  el: '#root',
  router: router,
  store: store,
  mounted() {
    if (window.localStorage.getItem('token')){

      // set acl permission
      this.$access('user')
    }
  },
  render: h => h(App)
})
```

**Comment by leonardovilarinho** [comment]
The correct in this conditional would be:
```
if (window.localStorage.getItem('token') !== null)
```

**Comment by pymarco** [comment]
Setting `$access('user')` in the `mounted` method of the Vue instance does not work for me. I even tried `beforeCreate` but still the check against init is causing failure before I am able to change $access.

**Comment by leonardovilarinho** [comment]
Is any error displayed on the screen? @pymarco

**Comment by pymarco** [comment]
Sorry, no error. Learning confusion on my part.
