### ISSUE TITLE
Middleware: should be optional

### ISSUE THREAD

**Issue by jesusvilla** [leonardovilarinho/vue-acl#82]
It should be optional, and everything indicates that it should be after your [last commit](https://github.com/leonardovilarinho/vue-acl/commit/7cb5fbb6744412d7a5c024bb985d29d305b6f5f0) but this is not reflected in your dist folder.
`yarn run build` fixed it

**Comment by ErickZH** [comment]
@leonardovilarinho is right @jesusvilla

**Comment by leonardovilarinho** [comment]
Sorry, I even ran the yarn build, but I ended up forgetting to publish.

Published now!
