### ISSUE TITLE
Middleware doesn't seem to work

### ISSUE THREAD

**Issue by alessandrodsouza** [leonardovilarinho/vue-acl#87]
middleware function doesn't execute on route change.

**Comment by DogfightMatthijs** [comment]
Same here. @alessandrodsouza  have you managed to get it working?
Edit: Seems that i had to update to vue-acl to v4.1.10.

**Comment by leonardovilarinho** [comment]
Hello, middleware has the sole purpose of being executed before the application is started. So you can start the application with a permission set for the user.

Perhaps the best name for it is `onStartup` and not` middleware`. To make a kind of "middleware" you can use a watch on the $route object.
