### ISSUE TITLE
mixin.js:65 [vue-acl] / not have rule

### ISSUE THREAD

**Issue by xianbinKit** [leonardovilarinho/vue-acl#88]
router

```
 [
  {
    path: '',
    component: () => import('@/layouts/main/Main.vue'),
    children: [
      {
        path: '/',
        redirect: '/dashboard',
        meta: {
          rule: 'isPublic'
        }
      },
      {
        path: '/dashboard',
        name: 'dashboard',
        component: () => import('@/views/dashboard'),
        meta: {
          pageTitle: 'Dashboard',
          rule: 'isSignedIn'
        }
      }]
  },
  {
    path: '',
    component: () => import('@/layouts/full-page/FullPage.vue'),
    children: [

      {
        path: '/pages/login',
        name: 'login',
        component: () => import('@/views/pages/login/Login.vue'),
        meta: {
          rule: 'isPublic'
        }
      },
      {
```

acl

```
const acl = new AclCreate({
  initial: initialRole,
  notfound: '/pages/not-authorized',
  router,
  acceptLocalRules: true,
  globalRules: {
    admin: new AclRule('admin').generate(),
    editor: new AclRule('editor').or('admin').generate(),
    accountant: new AclRule('accountant').generate(),
    isPublic: new AclRule('public').or('admin').or('user').generate(),
    isSignedIn: new AclRule('user').or('lmnp').or('admin').or('accountant').generate()
  },
```

Hello, could you help me please ?  

I get this error, sometime...... I don't know how and where I made wrong

**Comment by dikymury** [comment]
make initialRole role in acl.js
intialRole can be get in localStorage or make first initialRole
example : 
let initialRole = 'admin'
const acl = new AclCreate({
  initial: initialRole,
  notfound: '/pages/not-authorized',
  router,
  acceptLocalRules: true,
  globalRules: {
    admin: new AclRule('admin').generate(),
    editor: new AclRule('editor').or('admin').generate(),
    accountant: new AclRule('accountant').generate(),
    isPublic: new AclRule('public').or('admin').or('user').generate(),
    isSignedIn: new AclRule('user').or('lmnp').or('admin').or('accountant').generate()
  }
})

**Comment by leonardovilarinho** [comment]
Hello, you need to declare a permission for the mother route as well, you only declared in the daughters.
